language: node_js
before_deploy:
- npm run build:package
- cd dist
deploy:
  provider: npm
  email: jenkins-reform@HMCTS.NET
  api_key:
    secure: XNV1KvwsU49tzejjqcKSbTN9ajVYstpR8cBLaOf0bSFzwoyApGm2u4TaHSSBOR12IpG2UDfzC6qezy0UDOvG5c+E8J6/robMYS9a92cEceHjbeLsO3Yn1EzIf2WDL6TRwNoWb6fepCXpcYuh78CQFqkoD1Sy44CGfjgNm4r8PhDd5tt6n8TA+D6acMTj+t5cy5XpSF0D5y9ofo07yv2XSybx3qt25Jn2Of254rr7qlWvReXBXGiWIzfMcxOYST5IIRVPt81n7PeqmpjzDuwpV7FGpFYROMS239r7De7vNnuybyyKCm5a+2LScNmAOObMK9TAnkyrmBeHta4u4B5arwTC5RDLYavjncp03I2BenFyxQoaSiKKDsCNb0uaCFJwvqC4E7852uOwWHnqemhVkXUUyhRhI3X2KDcath+lfonwyhYXauqyTY2S2d2LWDZ0md84zyCeVe35pLHmK6U9+FWwGcotoZCsB+fnbB3YzRZHoWdZz4qfdWwxAZK2oxI0W0AF+x09Z5PNBbhPo1EfWDpBaJX/udGCI6bdxvlpGda4cJAGloRT4xNEecbhYfG2wOzsOiPpxXibe6o+j7Lwb1966zCChOQQ0LOnwNPXUNyyF815M30UDCw1TsnJnp/HRCIaBh92HqRoICdew308ups4c0t+oHpCLnPTf0s+Fno=
  on:
    tags: true
    repo: hmcts/rpa-accessmanagement-frontend-lib
